---
services:
  dnsmasq:
    image: pengshp/dnsmasq:latest
    container_name: dnsmasq-c
    volumes:
      - type: bind
        source: ./config
        target: /etc/dnsmasq.d/
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
