---
services:
  jsoncrack:
    image: enmanuelmoreira/jsoncrack:latest
    container_name: jsoncrack-c
    # ports:
    #   - "8888:8080"
    restart: always
    networks:
      - proxy
    labels:
      - "diun.enable=true"
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.jsoncrack-secure.entrypoints=websecure"
      - "traefik.http.routers.jsoncrack-secure.tls=true"
      - "traefik.http.routers.jsoncrack-secure.rule=Host(`jsoncrack.esxi.lan`)"
      - "traefik.http.routers.jsoncrack-secure.service=jsoncrack-service"
      - "traefik.http.services.jsoncrack-service.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
