---
services:
  voapi:
    image: voapi/voapi:latest
    restart: always
    command: --log-dir /app/logs
    # ports:
    #   - "3000:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      # - SQL_DSN=voapi:voapipass@tcp(host.docker.internal:3306)/voapi?charset=utf8mb4&parseTime=True&loc=Local
      - REDIS_CONN_STRING=redis://redis
      - SESSION_SECRET=<4eC6xxxxxxxxxxWEEs>
      - TZ=Asia/Shanghai
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - proxy
      - default
    labels:
      - "diun.enable=true"
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.voapi-secure.entrypoints=websecure"
      - "traefik.http.routers.voapi-secure.tls=true"
      - "traefik.http.routers.voapi-secure.rule=Host(`voapi.esxi.lan`)"
      - "traefik.http.routers.voapi-secure.service=voapi-service"
      - "traefik.http.services.voapi-service.loadbalancer.server.port=3000"
    depends_on:
      - redis
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
  # db:
  #   image: mariadb:lts
  #   command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   restart: always
  #   environment:
  #     - MYSQL_USER=voapi
  #     - MYSQL_PASSWORD=voapipass
  #     - MYSQL_DATABASE=voapi
  #     - TZ='Asia/Shanghai'
  #   volumes:
  #     - ./db:/var/lib/mysql
  #   networks:
  #     - default

  redis:
    image: redis:7.2
    networks:
      - default
    restart: always

networks:
  proxy:
    external: true
