---
services:
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools-c
    environment:
      - UID=1000
      - GID=1000
    networks:
      - proxy
    restart: always
    labels:
      - "diun.enable=true"
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.it-secure.entrypoints=websecure"
      - "traefik.http.routers.it-secure.tls=true"
      - "traefik.http.routers.it-secure.rule=Host(`it.esxi.lan`)"
      - "traefik.http.routers.it-secure.service=it-service"
      - "traefik.http.services.it-service.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
