---
services:
  bitwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden-c
    volumes:
      - ./data:/data
    restart: always
    networks:
      - proxy
    environment:
      DOMAIN: "${DOMAIN}"
      EXPERIMENTAL_CLIENT_FEATURE_FLAGS: "${EXPERIMENTAL_CLIENT_FEATURE_FLAGS}"
    labels:
      - "diun.enable=true"
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.bitwarden-secure.entrypoints=websecure"
      - "traefik.http.routers.bitwarden-secure.tls=true"
      - "traefik.http.routers.bitwarden-secure.rule=Host(`bitwarden.esxi.lan`)"
      - "traefik.http.routers.bitwarden-secure.service=bitwarden-service"
      - "traefik.http.services.bitwarden-service.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
