---
services:
  ntfy:
    image: binwiederhier/ntfy:latest
    restart: unless-stopped
    networks:
      - proxy
    environment:
      NTFY_BASE_URL: http://ntfy.esxi.lan
      NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
      NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_BEHIND_PROXY: true
      NTFY_ATTACHMENT_CACHE_DIR: /var/lib/ntfy/attachments
      NTFY_ENABLE_LOGIN: true
    volumes:
      - ./data:/var/lib/ntfy
    command: serve
    labels:
      - "diun.enable=true"
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.ntfy.entrypoints=websecure"
      - "traefik.http.routers.ntfy.tls=true"
      - "traefik.http.routers.ntfy.rule=Host(`ntfy.esxi.lan`)"
      - "traefik.http.routers.ntfy.service=ntfy-service"
      - "traefik.http.services.ntfy-service.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
