# static configuration
core:
  defaultRuleSyntax: v3

global:
  checkNewVersion: false
  sendAnonymousUsage: false

accessLog: {}

log:
  level: INFO # ERROR

api:
  dashboard: true
  insecure: true
  debug: false

metrics:
  addInternals: true
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    entryPoint: metrics

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
  metrics:
    address: :8082

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    # defaultRule: Host(`{{ normalize .Name }}.esxi.lan`)
    exposedByDefault: false
    watch: true
  file:
    directory: /etc/traefik/conf/
    watch: true
