---
services:
  Aria2-Pro:
    image: p3terx/aria2-pro
    container_name: aria2-pro
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - RPC_SECRET=zxcv
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Shanghai
    volumes:
      - ${PWD}/aria2-config:/config
      - ./dl:/downloads
    network_mode: host
    #    network_mode: bridge
    #    ports:
    #      - 6800:6800
    #      - 6888:6888
    #      - 6888:6888/udp
    restart: unless-stopped

  AriaNg:
    image: p3terx/ariang
    container_name: ariang
    command: --port 6880
    network_mode: host
    depends_on:
      - Aria2-Pro
    restart: unless-stopped
