---
services:
  portainer:
    image: portainer/portainer-ce:2.27.0
    container_name: portainer-c
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/xdl/docker/portainer/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.portainer-secure.entrypoints=websecure"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.rule=Host(`docker.esxi.lan`)"
      - "traefik.http.routers.portainer-secure.service=portainer-service"
      - "traefik.http.services.portainer-service.loadbalancer.server.port=9000"

networks:
  proxy:
    external: true
